on:
  push:
    branches:
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: microsoft/playwright-github-action@v1
      - name: Install Playwright Browsers
        run: npm init playwright@latest
